// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.transform

import aws.sdk.kotlin.services.ec2.model.AccountAttribute
import aws.sdk.kotlin.services.ec2.model.AccountAttributeValue
import aws.smithy.kotlin.runtime.serde.Deserializer
import aws.smithy.kotlin.runtime.serde.SdkFieldDescriptor
import aws.smithy.kotlin.runtime.serde.SdkObjectDescriptor
import aws.smithy.kotlin.runtime.serde.SerialKind
import aws.smithy.kotlin.runtime.serde.asSdkSerializable
import aws.smithy.kotlin.runtime.serde.deserializeList
import aws.smithy.kotlin.runtime.serde.deserializeMap
import aws.smithy.kotlin.runtime.serde.deserializeStruct
import aws.smithy.kotlin.runtime.serde.field
import aws.smithy.kotlin.runtime.serde.serializeList
import aws.smithy.kotlin.runtime.serde.serializeMap
import aws.smithy.kotlin.runtime.serde.serializeStruct
import aws.smithy.kotlin.runtime.serde.xml.XmlCollectionName
import aws.smithy.kotlin.runtime.serde.xml.XmlDeserializer
import aws.smithy.kotlin.runtime.serde.xml.XmlNamespace
import aws.smithy.kotlin.runtime.serde.xml.XmlSerialName

internal fun deserializeAccountAttributeDocument(deserializer: Deserializer): AccountAttribute {
    val builder = AccountAttribute.Builder()
    val ATTRIBUTENAME_DESCRIPTOR = SdkFieldDescriptor(SerialKind.String, XmlSerialName("attributeName"))
    val ATTRIBUTEVALUES_DESCRIPTOR = SdkFieldDescriptor(SerialKind.List, XmlSerialName("attributeValueSet"), XmlCollectionName("item"))
    val OBJ_DESCRIPTOR = SdkObjectDescriptor.build {
        trait(XmlSerialName("AccountAttribute"))
        trait(XmlNamespace("http://ec2.amazonaws.com/doc/2016-11-15"))
        field(ATTRIBUTENAME_DESCRIPTOR)
        field(ATTRIBUTEVALUES_DESCRIPTOR)
    }

    deserializer.deserializeStruct(OBJ_DESCRIPTOR) {
        loop@while (true) {
            when (findNextFieldIndex()) {
                ATTRIBUTENAME_DESCRIPTOR.index -> builder.attributeName = deserializeString()
                ATTRIBUTEVALUES_DESCRIPTOR.index -> builder.attributeValues =
                    deserializer.deserializeList(ATTRIBUTEVALUES_DESCRIPTOR) {
                        val col0 = mutableListOf<AccountAttributeValue>()
                        while (hasNextElement()) {
                            val el0 = if (nextHasValue()) { deserializeAccountAttributeValueDocument(deserializer) } else { deserializeNull(); continue }
                            col0.add(el0)
                        }
                        col0
                    }
                null -> break@loop
                else -> skipValue()
            }
        }
    }
    return builder.build()
}
