// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.polly.model



sealed class Engine {

    abstract val value: kotlin.String

    object Neural : aws.sdk.kotlin.services.polly.model.Engine() {
        override val value: kotlin.String = "neural"
        override fun toString(): kotlin.String = value
    }

    object Standard : aws.sdk.kotlin.services.polly.model.Engine() {
        override val value: kotlin.String = "standard"
        override fun toString(): kotlin.String = value
    }

    data class SdkUnknown(override val value: kotlin.String) : aws.sdk.kotlin.services.polly.model.Engine() {
        override fun toString(): kotlin.String = value
    }

    companion object {
        /**
         * Convert a raw value to one of the sealed variants or [SdkUnknown]
         */
        fun fromValue(str: kotlin.String): aws.sdk.kotlin.services.polly.model.Engine = when(str) {
            "neural" -> Neural
            "standard" -> Standard
            else -> SdkUnknown(str)
        }

        /**
         * Get a list of all possible variants
         */
        fun values(): kotlin.collections.List<aws.sdk.kotlin.services.polly.model.Engine> = listOf(
            Neural,
            Standard
        )
    }
}
