// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.polly.model



sealed class TextType {

    abstract val value: kotlin.String

    object Ssml : aws.sdk.kotlin.services.polly.model.TextType() {
        override val value: kotlin.String = "ssml"
        override fun toString(): kotlin.String = value
    }

    object Text : aws.sdk.kotlin.services.polly.model.TextType() {
        override val value: kotlin.String = "text"
        override fun toString(): kotlin.String = value
    }

    data class SdkUnknown(override val value: kotlin.String) : aws.sdk.kotlin.services.polly.model.TextType() {
        override fun toString(): kotlin.String = value
    }

    companion object {
        /**
         * Convert a raw value to one of the sealed variants or [SdkUnknown]
         */
        fun fromValue(str: kotlin.String): aws.sdk.kotlin.services.polly.model.TextType = when(str) {
            "ssml" -> Ssml
            "text" -> Text
            else -> SdkUnknown(str)
        }

        /**
         * Get a list of all possible variants
         */
        fun values(): kotlin.collections.List<aws.sdk.kotlin.services.polly.model.TextType> = listOf(
            Ssml,
            Text
        )
    }
}
