// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



sealed class AddressAttributeName {

    abstract val value: kotlin.String

    object DomainName : aws.sdk.kotlin.services.ec2.model.AddressAttributeName() {
        override val value: kotlin.String = "domain-name"
        override fun toString(): kotlin.String = value
    }

    data class SdkUnknown(override val value: kotlin.String) : aws.sdk.kotlin.services.ec2.model.AddressAttributeName() {
        override fun toString(): kotlin.String = value
    }

    companion object {
        /**
         * Convert a raw value to one of the sealed variants or [SdkUnknown]
         */
        fun fromValue(str: kotlin.String): aws.sdk.kotlin.services.ec2.model.AddressAttributeName = when(str) {
            "domain-name" -> DomainName
            else -> SdkUnknown(str)
        }

        /**
         * Get a list of all possible variants
         */
        fun values(): kotlin.collections.List<aws.sdk.kotlin.services.ec2.model.AddressAttributeName> = listOf(
            DomainName
        )
    }
}
