// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model

import kotlin.collections.List

public sealed class BatchState {

    public abstract val value: kotlin.String

    public object Active : aws.sdk.kotlin.services.ec2.model.BatchState() {
        override val value: kotlin.String = "active"
        override fun toString(): kotlin.String = value
    }

    public object Cancelled : aws.sdk.kotlin.services.ec2.model.BatchState() {
        override val value: kotlin.String = "cancelled"
        override fun toString(): kotlin.String = value
    }

    public object CancelledRunning : aws.sdk.kotlin.services.ec2.model.BatchState() {
        override val value: kotlin.String = "cancelled_running"
        override fun toString(): kotlin.String = value
    }

    public object CancelledTerminatingInstances : aws.sdk.kotlin.services.ec2.model.BatchState() {
        override val value: kotlin.String = "cancelled_terminating"
        override fun toString(): kotlin.String = value
    }

    public object Failed : aws.sdk.kotlin.services.ec2.model.BatchState() {
        override val value: kotlin.String = "failed"
        override fun toString(): kotlin.String = value
    }

    public object Modifying : aws.sdk.kotlin.services.ec2.model.BatchState() {
        override val value: kotlin.String = "modifying"
        override fun toString(): kotlin.String = value
    }

    public object Submitted : aws.sdk.kotlin.services.ec2.model.BatchState() {
        override val value: kotlin.String = "submitted"
        override fun toString(): kotlin.String = value
    }

    public data class SdkUnknown(override val value: kotlin.String) : aws.sdk.kotlin.services.ec2.model.BatchState() {
        override fun toString(): kotlin.String = value
    }

    public companion object {
        /**
         * Convert a raw value to one of the sealed variants or [SdkUnknown]
         */
        public fun fromValue(str: kotlin.String): aws.sdk.kotlin.services.ec2.model.BatchState = when(str) {
            "active" -> Active
            "cancelled" -> Cancelled
            "cancelled_running" -> CancelledRunning
            "cancelled_terminating" -> CancelledTerminatingInstances
            "failed" -> Failed
            "modifying" -> Modifying
            "submitted" -> Submitted
            else -> SdkUnknown(str)
        }

        /**
         * Get a list of all possible variants
         */
        public fun values(): kotlin.collections.List<aws.sdk.kotlin.services.ec2.model.BatchState> = listOf(
            Active,
            Cancelled,
            CancelledRunning,
            CancelledTerminatingInstances,
            Failed,
            Modifying,
            Submitted
        )
    }
}
