// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



sealed class CancelSpotInstanceRequestState {

    abstract val value: kotlin.String

    object Active : aws.sdk.kotlin.services.ec2.model.CancelSpotInstanceRequestState() {
        override val value: kotlin.String = "active"
        override fun toString(): kotlin.String = value
    }

    object Cancelled : aws.sdk.kotlin.services.ec2.model.CancelSpotInstanceRequestState() {
        override val value: kotlin.String = "cancelled"
        override fun toString(): kotlin.String = value
    }

    object Closed : aws.sdk.kotlin.services.ec2.model.CancelSpotInstanceRequestState() {
        override val value: kotlin.String = "closed"
        override fun toString(): kotlin.String = value
    }

    object Completed : aws.sdk.kotlin.services.ec2.model.CancelSpotInstanceRequestState() {
        override val value: kotlin.String = "completed"
        override fun toString(): kotlin.String = value
    }

    object Open : aws.sdk.kotlin.services.ec2.model.CancelSpotInstanceRequestState() {
        override val value: kotlin.String = "open"
        override fun toString(): kotlin.String = value
    }

    data class SdkUnknown(override val value: kotlin.String) : aws.sdk.kotlin.services.ec2.model.CancelSpotInstanceRequestState() {
        override fun toString(): kotlin.String = value
    }

    companion object {
        /**
         * Convert a raw value to one of the sealed variants or [SdkUnknown]
         */
        fun fromValue(str: kotlin.String): aws.sdk.kotlin.services.ec2.model.CancelSpotInstanceRequestState = when(str) {
            "active" -> Active
            "cancelled" -> Cancelled
            "closed" -> Closed
            "completed" -> Completed
            "open" -> Open
            else -> SdkUnknown(str)
        }

        /**
         * Get a list of all possible variants
         */
        fun values(): kotlin.collections.List<aws.sdk.kotlin.services.ec2.model.CancelSpotInstanceRequestState> = listOf(
            Active,
            Cancelled,
            Closed,
            Completed,
            Open
        )
    }
}
