// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



public class CreateTransitGatewayConnectRequest private constructor(builder: Builder) {
    /**
     * Checks whether you have the required permissions for the action, without actually making the request, and provides an error response. If you have the required permissions, the error response is `DryRunOperation`. Otherwise, it is `UnauthorizedOperation`.
     */
    public val dryRun: kotlin.Boolean? = builder.dryRun
    /**
     * The Connect attachment options.
     */
    public val options: aws.sdk.kotlin.services.ec2.model.CreateTransitGatewayConnectRequestOptions? = builder.options
    /**
     * The tags to apply to the Connect attachment.
     */
    public val tagSpecifications: List<TagSpecification>? = builder.tagSpecifications
    /**
     * The ID of the transit gateway attachment. You can specify a VPC attachment or Amazon Web Services Direct Connect attachment.
     */
    public val transportTransitGatewayAttachmentId: kotlin.String? = builder.transportTransitGatewayAttachmentId

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.CreateTransitGatewayConnectRequest = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("CreateTransitGatewayConnectRequest(")
        append("dryRun=$dryRun,")
        append("options=$options,")
        append("tagSpecifications=$tagSpecifications,")
        append("transportTransitGatewayAttachmentId=$transportTransitGatewayAttachmentId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = dryRun?.hashCode() ?: 0
        result = 31 * result + (options?.hashCode() ?: 0)
        result = 31 * result + (tagSpecifications?.hashCode() ?: 0)
        result = 31 * result + (transportTransitGatewayAttachmentId?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as CreateTransitGatewayConnectRequest

        if (dryRun != other.dryRun) return false
        if (options != other.options) return false
        if (tagSpecifications != other.tagSpecifications) return false
        if (transportTransitGatewayAttachmentId != other.transportTransitGatewayAttachmentId) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.CreateTransitGatewayConnectRequest = Builder(this).apply(block).build()

    public class Builder {
        /**
         * Checks whether you have the required permissions for the action, without actually making the request, and provides an error response. If you have the required permissions, the error response is `DryRunOperation`. Otherwise, it is `UnauthorizedOperation`.
         */
        public var dryRun: kotlin.Boolean? = null
        /**
         * The Connect attachment options.
         */
        public var options: aws.sdk.kotlin.services.ec2.model.CreateTransitGatewayConnectRequestOptions? = null
        /**
         * The tags to apply to the Connect attachment.
         */
        public var tagSpecifications: List<TagSpecification>? = null
        /**
         * The ID of the transit gateway attachment. You can specify a VPC attachment or Amazon Web Services Direct Connect attachment.
         */
        public var transportTransitGatewayAttachmentId: kotlin.String? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.CreateTransitGatewayConnectRequest) : this() {
            this.dryRun = x.dryRun
            this.options = x.options
            this.tagSpecifications = x.tagSpecifications
            this.transportTransitGatewayAttachmentId = x.transportTransitGatewayAttachmentId
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.CreateTransitGatewayConnectRequest = CreateTransitGatewayConnectRequest(this)

        /**
         * construct an [aws.sdk.kotlin.services.ec2.model.CreateTransitGatewayConnectRequestOptions] inside the given [block]
         */
        public fun options(block: aws.sdk.kotlin.services.ec2.model.CreateTransitGatewayConnectRequestOptions.Builder.() -> kotlin.Unit) {
            this.options = aws.sdk.kotlin.services.ec2.model.CreateTransitGatewayConnectRequestOptions.invoke(block)
        }
    }
}
