// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class CreateCapacityReservationResponse private constructor(builder: Builder) {
    /**
     * Information about the Capacity Reservation.
     */
    val capacityReservation: aws.sdk.kotlin.services.ec2.model.CapacityReservation? = builder.capacityReservation

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.CreateCapacityReservationResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("CreateCapacityReservationResponse(")
        append("capacityReservation=$capacityReservation)")
    }

    override fun hashCode(): kotlin.Int {
        var result = capacityReservation?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as CreateCapacityReservationResponse

        if (capacityReservation != other.capacityReservation) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.CreateCapacityReservationResponse = Builder(this).apply(block).build()

    class Builder {
        /**
         * Information about the Capacity Reservation.
         */
        var capacityReservation: aws.sdk.kotlin.services.ec2.model.CapacityReservation? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.CreateCapacityReservationResponse) : this() {
            this.capacityReservation = x.capacityReservation
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.CreateCapacityReservationResponse = CreateCapacityReservationResponse(this)

        /**
         * construct an [aws.sdk.kotlin.services.ec2.model.CapacityReservation] inside the given [block]
         */
        fun capacityReservation(block: aws.sdk.kotlin.services.ec2.model.CapacityReservation.Builder.() -> kotlin.Unit) {
            this.capacityReservation = aws.sdk.kotlin.services.ec2.model.CapacityReservation.invoke(block)
        }
    }
}
