// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class DeleteFleetsResponse private constructor(builder: Builder) {
    /**
     * Information about the EC2 Fleets that are successfully deleted.
     */
    val successfulFleetDeletions: List<DeleteFleetSuccessItem>? = builder.successfulFleetDeletions
    /**
     * Information about the EC2 Fleets that are not successfully deleted.
     */
    val unsuccessfulFleetDeletions: List<DeleteFleetErrorItem>? = builder.unsuccessfulFleetDeletions

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.DeleteFleetsResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("DeleteFleetsResponse(")
        append("successfulFleetDeletions=$successfulFleetDeletions,")
        append("unsuccessfulFleetDeletions=$unsuccessfulFleetDeletions)")
    }

    override fun hashCode(): kotlin.Int {
        var result = successfulFleetDeletions?.hashCode() ?: 0
        result = 31 * result + (unsuccessfulFleetDeletions?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as DeleteFleetsResponse

        if (successfulFleetDeletions != other.successfulFleetDeletions) return false
        if (unsuccessfulFleetDeletions != other.unsuccessfulFleetDeletions) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.DeleteFleetsResponse = Builder(this).apply(block).build()

    class Builder {
        /**
         * Information about the EC2 Fleets that are successfully deleted.
         */
        var successfulFleetDeletions: List<DeleteFleetSuccessItem>? = null
        /**
         * Information about the EC2 Fleets that are not successfully deleted.
         */
        var unsuccessfulFleetDeletions: List<DeleteFleetErrorItem>? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.DeleteFleetsResponse) : this() {
            this.successfulFleetDeletions = x.successfulFleetDeletions
            this.unsuccessfulFleetDeletions = x.unsuccessfulFleetDeletions
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.DeleteFleetsResponse = DeleteFleetsResponse(this)
    }
}
