// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Contains the output of DescribeVpnGateways.
 */
public class DescribeVpnGatewaysResponse private constructor(builder: Builder) {
    /**
     * Information about one or more virtual private gateways.
     */
    public val vpnGateways: List<VpnGateway>? = builder.vpnGateways

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.DescribeVpnGatewaysResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("DescribeVpnGatewaysResponse(")
        append("vpnGateways=$vpnGateways)")
    }

    override fun hashCode(): kotlin.Int {
        var result = vpnGateways?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as DescribeVpnGatewaysResponse

        if (vpnGateways != other.vpnGateways) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.DescribeVpnGatewaysResponse = Builder(this).apply(block).build()

    public class Builder {
        /**
         * Information about one or more virtual private gateways.
         */
        public var vpnGateways: List<VpnGateway>? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.DescribeVpnGatewaysResponse) : this() {
            this.vpnGateways = x.vpnGateways
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.DescribeVpnGatewaysResponse = DescribeVpnGatewaysResponse(this)
    }
}
