// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



public class DescribeIdentityIdFormatResponse private constructor(builder: Builder) {
    /**
     * Information about the ID format for the resources.
     */
    public val statuses: List<IdFormat>? = builder.statuses

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.DescribeIdentityIdFormatResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("DescribeIdentityIdFormatResponse(")
        append("statuses=$statuses)")
    }

    override fun hashCode(): kotlin.Int {
        var result = statuses?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as DescribeIdentityIdFormatResponse

        if (statuses != other.statuses) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.DescribeIdentityIdFormatResponse = Builder(this).apply(block).build()

    public class Builder {
        /**
         * Information about the ID format for the resources.
         */
        public var statuses: List<IdFormat>? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.DescribeIdentityIdFormatResponse) : this() {
            this.statuses = x.statuses
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.DescribeIdentityIdFormatResponse = DescribeIdentityIdFormatResponse(this)
    }
}
