// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



public class DescribeVolumesModificationsResponse private constructor(builder: Builder) {
    /**
     * Token for pagination, null if there are no more results
     */
    public val nextToken: kotlin.String? = builder.nextToken
    /**
     * Information about the volume modifications.
     */
    public val volumesModifications: List<VolumeModification>? = builder.volumesModifications

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.DescribeVolumesModificationsResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("DescribeVolumesModificationsResponse(")
        append("nextToken=$nextToken,")
        append("volumesModifications=$volumesModifications)")
    }

    override fun hashCode(): kotlin.Int {
        var result = nextToken?.hashCode() ?: 0
        result = 31 * result + (volumesModifications?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as DescribeVolumesModificationsResponse

        if (nextToken != other.nextToken) return false
        if (volumesModifications != other.volumesModifications) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.DescribeVolumesModificationsResponse = Builder(this).apply(block).build()

    public class Builder {
        /**
         * Token for pagination, null if there are no more results
         */
        public var nextToken: kotlin.String? = null
        /**
         * Information about the volume modifications.
         */
        public var volumesModifications: List<VolumeModification>? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.DescribeVolumesModificationsResponse) : this() {
            this.nextToken = x.nextToken
            this.volumesModifications = x.volumesModifications
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.DescribeVolumesModificationsResponse = DescribeVolumesModificationsResponse(this)
    }
}
