// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Contains the output of DescribeVpnConnections.
 */
class DescribeVpnConnectionsResponse private constructor(builder: Builder) {
    /**
     * Information about one or more VPN connections.
     */
    val vpnConnections: List<VpnConnection>? = builder.vpnConnections

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.DescribeVpnConnectionsResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("DescribeVpnConnectionsResponse(")
        append("vpnConnections=$vpnConnections)")
    }

    override fun hashCode(): kotlin.Int {
        var result = vpnConnections?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as DescribeVpnConnectionsResponse

        if (vpnConnections != other.vpnConnections) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.DescribeVpnConnectionsResponse = Builder(this).apply(block).build()

    class Builder {
        /**
         * Information about one or more VPN connections.
         */
        var vpnConnections: List<VpnConnection>? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.DescribeVpnConnectionsResponse) : this() {
            this.vpnConnections = x.vpnConnections
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.DescribeVpnConnectionsResponse = DescribeVpnConnectionsResponse(this)
    }
}
