// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Contains information about an error that occurred when disabling fast snapshot restores.
 */
public class DisableFastSnapshotRestoreStateErrorItem private constructor(builder: Builder) {
    /**
     * The Availability Zone.
     */
    public val availabilityZone: kotlin.String? = builder.availabilityZone
    /**
     * The error.
     */
    public val error: aws.sdk.kotlin.services.ec2.model.DisableFastSnapshotRestoreStateError? = builder.error

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.DisableFastSnapshotRestoreStateErrorItem = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("DisableFastSnapshotRestoreStateErrorItem(")
        append("availabilityZone=$availabilityZone,")
        append("error=$error)")
    }

    override fun hashCode(): kotlin.Int {
        var result = availabilityZone?.hashCode() ?: 0
        result = 31 * result + (error?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as DisableFastSnapshotRestoreStateErrorItem

        if (availabilityZone != other.availabilityZone) return false
        if (error != other.error) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.DisableFastSnapshotRestoreStateErrorItem = Builder(this).apply(block).build()

    public class Builder {
        /**
         * The Availability Zone.
         */
        public var availabilityZone: kotlin.String? = null
        /**
         * The error.
         */
        public var error: aws.sdk.kotlin.services.ec2.model.DisableFastSnapshotRestoreStateError? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.DisableFastSnapshotRestoreStateErrorItem) : this() {
            this.availabilityZone = x.availabilityZone
            this.error = x.error
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.DisableFastSnapshotRestoreStateErrorItem = DisableFastSnapshotRestoreStateErrorItem(this)

        /**
         * construct an [aws.sdk.kotlin.services.ec2.model.DisableFastSnapshotRestoreStateError] inside the given [block]
         */
        public fun error(block: aws.sdk.kotlin.services.ec2.model.DisableFastSnapshotRestoreStateError.Builder.() -> kotlin.Unit) {
            this.error = aws.sdk.kotlin.services.ec2.model.DisableFastSnapshotRestoreStateError.invoke(block)
        }
    }
}
