// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model

import kotlin.collections.List

public sealed class EbsEncryptionSupport {

    public abstract val value: kotlin.String

    public object Supported : aws.sdk.kotlin.services.ec2.model.EbsEncryptionSupport() {
        override val value: kotlin.String = "supported"
        override fun toString(): kotlin.String = value
    }

    public object Unsupported : aws.sdk.kotlin.services.ec2.model.EbsEncryptionSupport() {
        override val value: kotlin.String = "unsupported"
        override fun toString(): kotlin.String = value
    }

    public data class SdkUnknown(override val value: kotlin.String) : aws.sdk.kotlin.services.ec2.model.EbsEncryptionSupport() {
        override fun toString(): kotlin.String = value
    }

    public companion object {
        /**
         * Convert a raw value to one of the sealed variants or [SdkUnknown]
         */
        public fun fromValue(str: kotlin.String): aws.sdk.kotlin.services.ec2.model.EbsEncryptionSupport = when(str) {
            "supported" -> Supported
            "unsupported" -> Unsupported
            else -> SdkUnknown(str)
        }

        /**
         * Get a list of all possible variants
         */
        public fun values(): kotlin.collections.List<aws.sdk.kotlin.services.ec2.model.EbsEncryptionSupport> = listOf(
            Supported,
            Unsupported
        )
    }
}
