// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes the Elastic Fabric Adapters for the instance type.
 */
public class EfaInfo private constructor(builder: Builder) {
    /**
     * The maximum number of Elastic Fabric Adapters for the instance type.
     */
    public val maximumEfaInterfaces: kotlin.Int? = builder.maximumEfaInterfaces

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.EfaInfo = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("EfaInfo(")
        append("maximumEfaInterfaces=$maximumEfaInterfaces)")
    }

    override fun hashCode(): kotlin.Int {
        var result = maximumEfaInterfaces ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as EfaInfo

        if (maximumEfaInterfaces != other.maximumEfaInterfaces) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.EfaInfo = Builder(this).apply(block).build()

    public class Builder {
        /**
         * The maximum number of Elastic Fabric Adapters for the instance type.
         */
        public var maximumEfaInterfaces: kotlin.Int? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.EfaInfo) : this() {
            this.maximumEfaInterfaces = x.maximumEfaInterfaces
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.EfaInfo = EfaInfo(this)
    }
}
