// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes the FPGAs for the instance type.
 */
public class FpgaInfo private constructor(builder: Builder) {
    /**
     * Describes the FPGAs for the instance type.
     */
    public val fpgas: List<FpgaDeviceInfo>? = builder.fpgas
    /**
     * The total memory of all FPGA accelerators for the instance type.
     */
    public val totalFpgaMemoryInMib: kotlin.Int? = builder.totalFpgaMemoryInMib

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.FpgaInfo = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("FpgaInfo(")
        append("fpgas=$fpgas,")
        append("totalFpgaMemoryInMib=$totalFpgaMemoryInMib)")
    }

    override fun hashCode(): kotlin.Int {
        var result = fpgas?.hashCode() ?: 0
        result = 31 * result + (totalFpgaMemoryInMib ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as FpgaInfo

        if (fpgas != other.fpgas) return false
        if (totalFpgaMemoryInMib != other.totalFpgaMemoryInMib) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.FpgaInfo = Builder(this).apply(block).build()

    public class Builder {
        /**
         * Describes the FPGAs for the instance type.
         */
        public var fpgas: List<FpgaDeviceInfo>? = null
        /**
         * The total memory of all FPGA accelerators for the instance type.
         */
        public var totalFpgaMemoryInMib: kotlin.Int? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.FpgaInfo) : this() {
            this.fpgas = x.fpgas
            this.totalFpgaMemoryInMib = x.totalFpgaMemoryInMib
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.FpgaInfo = FpgaInfo(this)
    }
}
