// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes the attachment of a VPC to an internet gateway or an egress-only internet
 * gateway.
 */
class InternetGatewayAttachment private constructor(builder: Builder) {
    /**
     * The current state of the attachment. For an internet gateway, the state is
     * available when attached to a VPC; otherwise, this value is not
     * returned.
     */
    val state: aws.sdk.kotlin.services.ec2.model.AttachmentStatus? = builder.state
    /**
     * The ID of the VPC.
     */
    val vpcId: kotlin.String? = builder.vpcId

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.InternetGatewayAttachment = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("InternetGatewayAttachment(")
        append("state=$state,")
        append("vpcId=$vpcId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = state?.hashCode() ?: 0
        result = 31 * result + (vpcId?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as InternetGatewayAttachment

        if (state != other.state) return false
        if (vpcId != other.vpcId) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.InternetGatewayAttachment = Builder(this).apply(block).build()

    class Builder {
        /**
         * The current state of the attachment. For an internet gateway, the state is
         * available when attached to a VPC; otherwise, this value is not
         * returned.
         */
        var state: aws.sdk.kotlin.services.ec2.model.AttachmentStatus? = null
        /**
         * The ID of the VPC.
         */
        var vpcId: kotlin.String? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.InternetGatewayAttachment) : this() {
            this.state = x.state
            this.vpcId = x.vpcId
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.InternetGatewayAttachment = InternetGatewayAttachment(this)
    }
}
