// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model

import aws.smithy.kotlin.runtime.time.Instant

class ModifySnapshotTierResponse private constructor(builder: Builder) {
    /**
     * The ID of the snapshot.
     */
    val snapshotId: kotlin.String? = builder.snapshotId
    /**
     * The date and time when the archive process was started.
     */
    val tieringStartTime: aws.smithy.kotlin.runtime.time.Instant? = builder.tieringStartTime

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.ModifySnapshotTierResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("ModifySnapshotTierResponse(")
        append("snapshotId=$snapshotId,")
        append("tieringStartTime=$tieringStartTime)")
    }

    override fun hashCode(): kotlin.Int {
        var result = snapshotId?.hashCode() ?: 0
        result = 31 * result + (tieringStartTime?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as ModifySnapshotTierResponse

        if (snapshotId != other.snapshotId) return false
        if (tieringStartTime != other.tieringStartTime) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.ModifySnapshotTierResponse = Builder(this).apply(block).build()

    class Builder {
        /**
         * The ID of the snapshot.
         */
        var snapshotId: kotlin.String? = null
        /**
         * The date and time when the archive process was started.
         */
        var tieringStartTime: aws.smithy.kotlin.runtime.time.Instant? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.ModifySnapshotTierResponse) : this() {
            this.snapshotId = x.snapshotId
            this.tieringStartTime = x.tieringStartTime
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.ModifySnapshotTierResponse = ModifySnapshotTierResponse(this)
    }
}
