// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes the placement of an instance.
 */
class PlacementResponse private constructor(builder: Builder) {
    /**
     * The name of the placement group that the instance is in.
     */
    val groupName: kotlin.String? = builder.groupName

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.PlacementResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("PlacementResponse(")
        append("groupName=$groupName)")
    }

    override fun hashCode(): kotlin.Int {
        var result = groupName?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as PlacementResponse

        if (groupName != other.groupName) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.PlacementResponse = Builder(this).apply(block).build()

    class Builder {
        /**
         * The name of the placement group that the instance is in.
         */
        var groupName: kotlin.String? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.PlacementResponse) : this() {
            this.groupName = x.groupName
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.PlacementResponse = PlacementResponse(this)
    }
}
