// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes a prefix list ID.
 */
class PrefixListId private constructor(builder: Builder) {
    /**
     * A description for the security group rule that references this prefix list ID.
     * Constraints: Up to 255 characters in length. Allowed characters are a-z, A-Z, 0-9,
     * spaces, and ._-:/()#,@&#91;&#93;+=;{}!$*
     */
    val description: kotlin.String? = builder.description
    /**
     * The ID of the prefix.
     */
    val prefixListId: kotlin.String? = builder.prefixListId

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.PrefixListId = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("PrefixListId(")
        append("description=$description,")
        append("prefixListId=$prefixListId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = description?.hashCode() ?: 0
        result = 31 * result + (prefixListId?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as PrefixListId

        if (description != other.description) return false
        if (prefixListId != other.prefixListId) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.PrefixListId = Builder(this).apply(block).build()

    class Builder {
        /**
         * A description for the security group rule that references this prefix list ID.
         * Constraints: Up to 255 characters in length. Allowed characters are a-z, A-Z, 0-9,
         * spaces, and ._-:/()#,@&#91;&#93;+=;{}!$*
         */
        var description: kotlin.String? = null
        /**
         * The ID of the prefix.
         */
        var prefixListId: kotlin.String? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.PrefixListId) : this() {
            this.description = x.description
            this.prefixListId = x.prefixListId
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.PrefixListId = PrefixListId(this)
    }
}
