// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes a VPC with a security group that references your security group.
 */
class SecurityGroupReference private constructor(builder: Builder) {
    /**
     * The ID of your security group.
     */
    val groupId: kotlin.String? = builder.groupId
    /**
     * The ID of the VPC with the referencing security group.
     */
    val referencingVpcId: kotlin.String? = builder.referencingVpcId
    /**
     * The ID of the VPC peering connection.
     */
    val vpcPeeringConnectionId: kotlin.String? = builder.vpcPeeringConnectionId

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.SecurityGroupReference = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("SecurityGroupReference(")
        append("groupId=$groupId,")
        append("referencingVpcId=$referencingVpcId,")
        append("vpcPeeringConnectionId=$vpcPeeringConnectionId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = groupId?.hashCode() ?: 0
        result = 31 * result + (referencingVpcId?.hashCode() ?: 0)
        result = 31 * result + (vpcPeeringConnectionId?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as SecurityGroupReference

        if (groupId != other.groupId) return false
        if (referencingVpcId != other.referencingVpcId) return false
        if (vpcPeeringConnectionId != other.vpcPeeringConnectionId) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.SecurityGroupReference = Builder(this).apply(block).build()

    class Builder {
        /**
         * The ID of your security group.
         */
        var groupId: kotlin.String? = null
        /**
         * The ID of the VPC with the referencing security group.
         */
        var referencingVpcId: kotlin.String? = null
        /**
         * The ID of the VPC peering connection.
         */
        var vpcPeeringConnectionId: kotlin.String? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.SecurityGroupReference) : this() {
            this.groupId = x.groupId
            this.referencingVpcId = x.referencingVpcId
            this.vpcPeeringConnectionId = x.vpcPeeringConnectionId
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.SecurityGroupReference = SecurityGroupReference(this)
    }
}
