// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model

import kotlin.collections.List

public sealed class SubnetCidrBlockStateCode {

    public abstract val value: kotlin.String

    public object Associated : aws.sdk.kotlin.services.ec2.model.SubnetCidrBlockStateCode() {
        override val value: kotlin.String = "associated"
        override fun toString(): kotlin.String = value
    }

    public object Associating : aws.sdk.kotlin.services.ec2.model.SubnetCidrBlockStateCode() {
        override val value: kotlin.String = "associating"
        override fun toString(): kotlin.String = value
    }

    public object Disassociated : aws.sdk.kotlin.services.ec2.model.SubnetCidrBlockStateCode() {
        override val value: kotlin.String = "disassociated"
        override fun toString(): kotlin.String = value
    }

    public object Disassociating : aws.sdk.kotlin.services.ec2.model.SubnetCidrBlockStateCode() {
        override val value: kotlin.String = "disassociating"
        override fun toString(): kotlin.String = value
    }

    public object Failed : aws.sdk.kotlin.services.ec2.model.SubnetCidrBlockStateCode() {
        override val value: kotlin.String = "failed"
        override fun toString(): kotlin.String = value
    }

    public object Failing : aws.sdk.kotlin.services.ec2.model.SubnetCidrBlockStateCode() {
        override val value: kotlin.String = "failing"
        override fun toString(): kotlin.String = value
    }

    public data class SdkUnknown(override val value: kotlin.String) : aws.sdk.kotlin.services.ec2.model.SubnetCidrBlockStateCode() {
        override fun toString(): kotlin.String = value
    }

    public companion object {
        /**
         * Convert a raw value to one of the sealed variants or [SdkUnknown]
         */
        public fun fromValue(str: kotlin.String): aws.sdk.kotlin.services.ec2.model.SubnetCidrBlockStateCode = when(str) {
            "associated" -> Associated
            "associating" -> Associating
            "disassociated" -> Disassociated
            "disassociating" -> Disassociating
            "failed" -> Failed
            "failing" -> Failing
            else -> SdkUnknown(str)
        }

        /**
         * Get a list of all possible variants
         */
        public fun values(): kotlin.collections.List<aws.sdk.kotlin.services.ec2.model.SubnetCidrBlockStateCode> = listOf(
            Associated,
            Associating,
            Disassociated,
            Disassociating,
            Failed,
            Failing
        )
    }
}
