// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * The BGP options for the Connect attachment.
 */
class TransitGatewayConnectRequestBgpOptions private constructor(builder: Builder) {
    /**
     * The peer Autonomous System Number (ASN).
     */
    val peerAsn: kotlin.Long? = builder.peerAsn

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.TransitGatewayConnectRequestBgpOptions = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("TransitGatewayConnectRequestBgpOptions(")
        append("peerAsn=$peerAsn)")
    }

    override fun hashCode(): kotlin.Int {
        var result = peerAsn?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as TransitGatewayConnectRequestBgpOptions

        if (peerAsn != other.peerAsn) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.TransitGatewayConnectRequestBgpOptions = Builder(this).apply(block).build()

    class Builder {
        /**
         * The peer Autonomous System Number (ASN).
         */
        var peerAsn: kotlin.Long? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.TransitGatewayConnectRequestBgpOptions) : this() {
            this.peerAsn = x.peerAsn
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.TransitGatewayConnectRequestBgpOptions = TransitGatewayConnectRequestBgpOptions(this)
    }
}
