// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes the burstable performance instance whose credit option for CPU usage was not
 * modified.
 */
class UnsuccessfulInstanceCreditSpecificationItem private constructor(builder: Builder) {
    /**
     * The applicable error for the burstable performance instance whose credit option for
     * CPU usage was not modified.
     */
    val error: aws.sdk.kotlin.services.ec2.model.UnsuccessfulInstanceCreditSpecificationItemError? = builder.error
    /**
     * The ID of the instance.
     */
    val instanceId: kotlin.String? = builder.instanceId

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.UnsuccessfulInstanceCreditSpecificationItem = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("UnsuccessfulInstanceCreditSpecificationItem(")
        append("error=$error,")
        append("instanceId=$instanceId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = error?.hashCode() ?: 0
        result = 31 * result + (instanceId?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as UnsuccessfulInstanceCreditSpecificationItem

        if (error != other.error) return false
        if (instanceId != other.instanceId) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.UnsuccessfulInstanceCreditSpecificationItem = Builder(this).apply(block).build()

    class Builder {
        /**
         * The applicable error for the burstable performance instance whose credit option for
         * CPU usage was not modified.
         */
        var error: aws.sdk.kotlin.services.ec2.model.UnsuccessfulInstanceCreditSpecificationItemError? = null
        /**
         * The ID of the instance.
         */
        var instanceId: kotlin.String? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.UnsuccessfulInstanceCreditSpecificationItem) : this() {
            this.error = x.error
            this.instanceId = x.instanceId
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.UnsuccessfulInstanceCreditSpecificationItem = UnsuccessfulInstanceCreditSpecificationItem(this)

        /**
         * construct an [aws.sdk.kotlin.services.ec2.model.UnsuccessfulInstanceCreditSpecificationItemError] inside the given [block]
         */
        fun error(block: aws.sdk.kotlin.services.ec2.model.UnsuccessfulInstanceCreditSpecificationItemError.Builder.() -> kotlin.Unit) {
            this.error = aws.sdk.kotlin.services.ec2.model.UnsuccessfulInstanceCreditSpecificationItemError.invoke(block)
        }
    }
}
