// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes the volume status.
 */
class VolumeStatusItem private constructor(builder: Builder) {
    /**
     * The details of the operation.
     */
    val actions: List<VolumeStatusAction>? = builder.actions
    /**
     * Information about the instances to which the volume is attached.
     */
    val attachmentStatuses: List<VolumeStatusAttachmentStatus>? = builder.attachmentStatuses
    /**
     * The Availability Zone of the volume.
     */
    val availabilityZone: kotlin.String? = builder.availabilityZone
    /**
     * A list of events associated with the volume.
     */
    val events: List<VolumeStatusEvent>? = builder.events
    /**
     * The Amazon Resource Name (ARN) of the Outpost.
     */
    val outpostArn: kotlin.String? = builder.outpostArn
    /**
     * The volume ID.
     */
    val volumeId: kotlin.String? = builder.volumeId
    /**
     * The volume status.
     */
    val volumeStatus: aws.sdk.kotlin.services.ec2.model.VolumeStatusInfo? = builder.volumeStatus

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.VolumeStatusItem = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("VolumeStatusItem(")
        append("actions=$actions,")
        append("attachmentStatuses=$attachmentStatuses,")
        append("availabilityZone=$availabilityZone,")
        append("events=$events,")
        append("outpostArn=$outpostArn,")
        append("volumeId=$volumeId,")
        append("volumeStatus=$volumeStatus)")
    }

    override fun hashCode(): kotlin.Int {
        var result = actions?.hashCode() ?: 0
        result = 31 * result + (attachmentStatuses?.hashCode() ?: 0)
        result = 31 * result + (availabilityZone?.hashCode() ?: 0)
        result = 31 * result + (events?.hashCode() ?: 0)
        result = 31 * result + (outpostArn?.hashCode() ?: 0)
        result = 31 * result + (volumeId?.hashCode() ?: 0)
        result = 31 * result + (volumeStatus?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as VolumeStatusItem

        if (actions != other.actions) return false
        if (attachmentStatuses != other.attachmentStatuses) return false
        if (availabilityZone != other.availabilityZone) return false
        if (events != other.events) return false
        if (outpostArn != other.outpostArn) return false
        if (volumeId != other.volumeId) return false
        if (volumeStatus != other.volumeStatus) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.VolumeStatusItem = Builder(this).apply(block).build()

    class Builder {
        /**
         * The details of the operation.
         */
        var actions: List<VolumeStatusAction>? = null
        /**
         * Information about the instances to which the volume is attached.
         */
        var attachmentStatuses: List<VolumeStatusAttachmentStatus>? = null
        /**
         * The Availability Zone of the volume.
         */
        var availabilityZone: kotlin.String? = null
        /**
         * A list of events associated with the volume.
         */
        var events: List<VolumeStatusEvent>? = null
        /**
         * The Amazon Resource Name (ARN) of the Outpost.
         */
        var outpostArn: kotlin.String? = null
        /**
         * The volume ID.
         */
        var volumeId: kotlin.String? = null
        /**
         * The volume status.
         */
        var volumeStatus: aws.sdk.kotlin.services.ec2.model.VolumeStatusInfo? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.VolumeStatusItem) : this() {
            this.actions = x.actions
            this.attachmentStatuses = x.attachmentStatuses
            this.availabilityZone = x.availabilityZone
            this.events = x.events
            this.outpostArn = x.outpostArn
            this.volumeId = x.volumeId
            this.volumeStatus = x.volumeStatus
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.VolumeStatusItem = VolumeStatusItem(this)

        /**
         * construct an [aws.sdk.kotlin.services.ec2.model.VolumeStatusInfo] inside the given [block]
         */
        fun volumeStatus(block: aws.sdk.kotlin.services.ec2.model.VolumeStatusInfo.Builder.() -> kotlin.Unit) {
            this.volumeStatus = aws.sdk.kotlin.services.ec2.model.VolumeStatusInfo.invoke(block)
        }
    }
}
