// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.s3.transform

import aws.sdk.kotlin.services.s3.model.AnalyticsConfiguration
import aws.smithy.kotlin.runtime.serde.xml.XmlDeserializer

internal fun deserializeAnalyticsConfigurationPayload(payload: ByteArray): AnalyticsConfiguration {
    val deserializer = XmlDeserializer(payload)
    return deserializeAnalyticsConfigurationDocument(deserializer)
}
