// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.polly.transform

import aws.sdk.kotlin.services.polly.model.DescribeVoicesRequest
import aws.sdk.kotlin.services.polly.model.Engine
import aws.sdk.kotlin.services.polly.model.LanguageCode
import aws.smithy.kotlin.runtime.client.ExecutionContext
import aws.smithy.kotlin.runtime.http.HttpBody
import aws.smithy.kotlin.runtime.http.HttpMethod
import aws.smithy.kotlin.runtime.http.content.ByteArrayContent
import aws.smithy.kotlin.runtime.http.operation.HttpSerialize
import aws.smithy.kotlin.runtime.http.parameters
import aws.smithy.kotlin.runtime.http.request.HttpRequestBuilder
import aws.smithy.kotlin.runtime.http.request.url


internal class DescribeVoicesOperationSerializer: HttpSerialize<DescribeVoicesRequest> {
    override suspend fun serialize(context: ExecutionContext, input: DescribeVoicesRequest): HttpRequestBuilder {
        val builder = HttpRequestBuilder()
        builder.method = HttpMethod.GET

        builder.url {
            path = "/v1/voices"
            parameters {
                if (input.engine != null) append("Engine", input.engine.value)
                if (input.includeAdditionalLanguageCodes != false) append("IncludeAdditionalLanguageCodes", "${input.includeAdditionalLanguageCodes}")
                if (input.languageCode != null) append("LanguageCode", input.languageCode.value)
                if (input.nextToken != null) append("NextToken", input.nextToken)
            }
        }

        return builder
    }
}
