// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.dynamodb.model



/**
 * The description of the Time to Live (TTL) status on the specified table.
 */
class TimeToLiveDescription private constructor(builder: Builder) {
    /**
     * The name of the TTL attribute for items in the table.
     */
    val attributeName: kotlin.String? = builder.attributeName
    /**
     * The TTL status for the table.
     */
    val timeToLiveStatus: aws.sdk.kotlin.services.dynamodb.model.TimeToLiveStatus? = builder.timeToLiveStatus

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.dynamodb.model.TimeToLiveDescription = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("TimeToLiveDescription(")
        append("attributeName=$attributeName,")
        append("timeToLiveStatus=$timeToLiveStatus)")
    }

    override fun hashCode(): kotlin.Int {
        var result = attributeName?.hashCode() ?: 0
        result = 31 * result + (timeToLiveStatus?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as TimeToLiveDescription

        if (attributeName != other.attributeName) return false
        if (timeToLiveStatus != other.timeToLiveStatus) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.dynamodb.model.TimeToLiveDescription = Builder(this).apply(block).build()

    class Builder {
        /**
         * The name of the TTL attribute for items in the table.
         */
        var attributeName: kotlin.String? = null
        /**
         * The TTL status for the table.
         */
        var timeToLiveStatus: aws.sdk.kotlin.services.dynamodb.model.TimeToLiveStatus? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.dynamodb.model.TimeToLiveDescription) : this() {
            this.attributeName = x.attributeName
            this.timeToLiveStatus = x.timeToLiveStatus
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.dynamodb.model.TimeToLiveDescription = TimeToLiveDescription(this)
    }
}
