// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.s3.model



class GetBucketAccelerateConfigurationResponse private constructor(builder: Builder) {
    /**
     * The accelerate configuration of the bucket.
     */
    val status: aws.sdk.kotlin.services.s3.model.BucketAccelerateStatus? = builder.status

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.s3.model.GetBucketAccelerateConfigurationResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("GetBucketAccelerateConfigurationResponse(")
        append("status=$status)")
    }

    override fun hashCode(): kotlin.Int {
        var result = status?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as GetBucketAccelerateConfigurationResponse

        if (status != other.status) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.s3.model.GetBucketAccelerateConfigurationResponse = Builder(this).apply(block).build()

    class Builder {
        /**
         * The accelerate configuration of the bucket.
         */
        var status: aws.sdk.kotlin.services.s3.model.BucketAccelerateStatus? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.s3.model.GetBucketAccelerateConfigurationResponse) : this() {
            this.status = x.status
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.s3.model.GetBucketAccelerateConfigurationResponse = GetBucketAccelerateConfigurationResponse(this)
    }
}
